name: Gerar Executavel Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixando o codigo
      uses: actions/checkout@v4

    - name: Configurando o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install selenium pyinstaller requests pandas openpyxl

    - name: Criar o arquivo .EXE
      shell: cmd
      run: |
        for %%f in (*.py) do pyinstaller --onefile --collect-all selenium "%%f"
        
    - name: Disponibilizar para Download
      uses: actions/upload-artifact@v4
      with:
        name: Executavel-Windows
        path: dist/
